from .paths import IMAGE_CURSOR
from .paths import IMAGE_ICON
from .paths import SOUND_1
from .paths import SOUND_2
from .paths import SOUND_3
from .paths import SOUND_4
from .paths import SOUND_5
from .paths import SOUND_6
from .paths import SOUND_7
from .paths import SOUND_8
from .paths import SOUND_9
from .paths import get_path
